### ISSUE TITLE
rtp_session_set_payload_type(session,97);

### ISSUE THREAD

**Issue by goog** [marlin688/amr-audio#1]
why 97 ?

**Comment by marlin688** [comment]
the payload type of H264 is 97

**Comment by goog** [comment]
Hi, if i want to transfer decoded audio data by rtp, which payload  to choose ?

**Comment by marlin688** [comment]
http://en.wikipedia.org/wiki/RTP_audio_video_profile

**Comment by goog** [comment]
thanks
